name: Deploy Hephaestus Registry

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, gaia]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Secrets
        env:
          HTPASSWD: ${{ secrets.REGISTRY_HTPASSWD }}
        run: |
          chmod +x scripts/ensure_secret.sh
          echo "REGISTRY_HTPASSWD_NAME=$(echo "$HTPASSWD" | ./scripts/ensure_secret.sh registry_htpasswd)" >> $GITHUB_ENV

      - name: Deploy Stack
        env:
          DOMAIN_NAME: ${{ vars.DOMAIN_NAME }}
        run: |
          chmod +x scripts/deploy.sh
          ./scripts/deploy.sh "hephaestus" docker-compose.yml
